eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
feign:
  hystrix:
    enabled: true

server:
  port: 18762
spring:
  application:
    name: service-hi
  #freemarker的配置
  http:
    encoding:
      force: true
      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates
  #数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lianxi.eurekaclient1.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


